<?php

//load transactions data
$data = array(
		'IDENTIFICATION_SHORTID' 	=> '',
		'CONNECTOR_ACCOUNT_HOLDER' 	=> '',
		'CONNECTOR_ACCOUNT_IBAN' 	=> '',
		'CONNECTOR_ACCOUNT_BIC' 	=> ''

);

$TransactionId = ($this->getMethod()->getInfoInstance()->getLastTransId() === false) ?  false : $this->getMethod()->getInfoInstance()->getLastTransId() ;

if ($TransactionId !== False)
	$data = Mage::getModel('hcd/transaction')->loadLastTransactionDataByUniqeId((string)$TransactionId);

// titel
echo $this->escapeHtml($this->getMethod()->getTitle()); ?>
{{pdf_row_separator}}
<?php echo $this->__('Holder') . " : " . $this->escapeHtml($data['CONNECTOR_ACCOUNT_HOLDER']) ?>
{{pdf_row_separator}}    
<?php echo $this->__('IBAN') . " : "  . $this->escapeHtml($data['CONNECTOR_ACCOUNT_IBAN']) ?>
{{pdf_row_separator}}
<?php echo $this->__('BIC') . " : "  . $this->escapeHtml($data['CONNECTOR_ACCOUNT_BIC']) ?>
{{pdf_row_separator}}
<?php echo $this->__('Identification'). " : " . $this->escapeHtml($data['IDENTIFICATION_SHORTID']) ?>

