<?php
/**
 * Extend pdf template and add invoice information
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present Heidelberger Payment GmbH. All rights reserved.
 *
 * @link  https://dev.heidelpay.de/magento
 *
 * @author  Jens Richter
 *
 * @package  Heidelpay
 * @subpackage Magento
 * @category Magento
 */
$data = array(
        'IDENTIFICATION_SHORTID'     => '',
        'CONNECTOR_ACCOUNT_HOLDER'     => '',
        'CONNECTOR_ACCOUNT_IBAN'     => '',
        'CONNECTOR_ACCOUNT_BIC'     => ''

);

$transactionId = ($this->getMethod()
        ->getInfoInstance()
        ->getLastTransId() === false) ?  false : $this->getMethod()->getInfoInstance()->getLastTransId();

if ($transactionId !== False)
    $data = Mage::getModel('hcd/transaction')->loadLastTransactionDataByUniqeId((string)$transactionId);

// title of the payment method
echo $this->escapeHtml($this->getMethod()->getTitle()); ?>
{{pdf_row_separator}}

    {{pdf_row_separator}}
<?php echo $this->escapeHtml($this->__('The booking contains:')); ?>
{{pdf_row_separator}}
<?php echo $this->escapeHtml($this->__('mandate reference ID') . " : "  . $data['ACCOUNT_IDENTIFICATION']) ?>
{{pdf_row_separator}}
<?php echo $this->escapeHtml($this->__('creditor identifier') . " : "  . $data['IDENTIFICATION_CREDITOR_ID']) ?>