<button type="button" title="MasterPass"
			class="btn-hcdmpa-info"
			onclick="window.open('https://www.mastercard.com/mc_us/wallet/learnmore/<?php 
	$lang = Mage::app()->getLocale()->getLocaleCode();
	switch ($lang) {
		case 'de_DE':
		case 'de_AT':
		case 'de_CH':
				echo 'de/DE';
				break;
		case 'fr_FR':
				echo 'fr/FR';
				break;
		case 'en_GB':
		case 'en_US':
		default:
				echo 'en/US';
				break;
	}?>')" 
	style="background: url('<?php echo Mage::getDesign()->getSkinUrl('images/hcd/');  ?>masterpass_100_28.jpg'
    ) 0 0 no-repeat;"
	></button>
<div class="hcd-masterpass-payment-data-info"><?php echo $this->getMethod()->getPaymentData();?></div>
