<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Payment Method') ?><span class="changelink"> <span class="separator">|</span> <a
        href="<?php echo Mage::getUrl('hcd/index/wallet',array('_secure'=>true, '_wallet' =>'hcdmpa')); ?>"
        onclick="window.location='<?php echo Mage::getUrl('hcd/index/wallet',array('_secure'=>true, '_wallet' =>'hcdmpa')); ?>';" style="text-transform: none; size: 10px; display: block;"><?php echo Mage::helper('hcd')->__('Change at MasterPass') ?> </a></span>
</dt>
<dd>
<button type="button" title="MasterPass"
			class="btn-hcdmpa-info"
			onclick="window.open('https://www.mastercard.com/mc_us/wallet/learnmore/<?php 
	$lang = Mage::app()->getLocale()->getLocaleCode();
	switch ($lang) {
		case 'de_DE':
		case 'de_AT':
		case 'de_CH':
				echo 'de/DE';
				break;
		case 'fr_FR':
				echo 'fr/FR';
				break;
		case 'en_GB':
		case 'en_US':
		default:
				echo 'en/US';
				break;
	}?>')" 
	style="background: url('<?php echo Mage::getDesign()->getSkinUrl('images/hcd/');  ?>masterpass_100_28.jpg'
    ) 0 0 no-repeat;"
	></button>
	<div class="hcd-masterpass-payment-data-info"><?php 
	$session = Mage::getSingleton('checkout/session');
		
	if ($session->getHcdWallet() !== false) {
			
			$hpdata = $session->getHcdWallet();
		
			echo (array_key_exists('mail', $hpdata)) ? $hpdata['mail'].'<br />' : '' ;
			echo (array_key_exists('brand', $hpdata)) ? Mage::helper('hcd')->__($hpdata['brand']).' ' : '' ;
			echo (array_key_exists('number', $hpdata)) ? $hpdata['number'].'<br/>' : '' ;
			echo (array_key_exists('expiryMonth', $hpdata)) ? Mage::helper('hcd')->__('Expires').' '.$hpdata['expiryMonth'].'/' : '' ;
			echo (array_key_exists('expiryYear', $hpdata)) ? $hpdata['expiryYear'] : '' ;
	}
	
	?></div>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Payment Method') ?>
</dt>
<?php endif; ?>

