<?php
    /** @var array $paymentInfo */
	$paymentInfo = $this->showPaymentInfo(); 
	if (!empty($paymentInfo)) :
?>
<!-- Heidelpay success payment information -->
<div class="block block-list block-compare">
<div class="block-title">
		<strong>
			<span>
			<?php
                printf('%s - %s', $this->__('payment information'), $paymentInfo['Title']);
			?>
			</span>
		</strong>
	</div>
	<div class="block-hcd-payment-info">
		<?php echo $paymentInfo['Message'] ?>
	</div>
</div>
<!-- End Heidelpay success payment information -->
<?php endif ?>
