<?php
/**
 * Direct debit form template
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present heidelpay GmbH. All rights reserved.
 *
 * @link  http://dev.heidelpay.com/magento
 *
 * @author  Jens Richter
 *
 * @package  Heidelpay
 * @subpackage Magento
 * @category Magento
 */

use HeidelpayCD_Edition_Model_System_Config_Source_Recognition as Recognition;

$code = $this->getMethodCode();

$path = 'payment/' . $code . '/';
$storeId = Mage::app()->getStore()->getId();
$recognition = Mage::getStoreConfig($path . 'recognition', $storeId);

/*
 * Look for customer recognition
 */

$hash = $this->getMethod()->getShippingHash();
$userData = array ();

$cId = $this->getMethod()->getCustomerId();

if ($cId != 0) {
    if ($recognition == Recognition::SAME_SHIPPING_ADDRESS) { // only if shipping address is unchanged
        $hash = $this->getMethod()->getShippingHash();
        $userData = $this->getMethod()->getCustomerData();
        if ($userData !== false && array_key_exists('payment_data', $userData)) {
            if ($userData ['payment_data'] ['SHIPPING_HASH'] != $hash)
                $userData = array();
        }
    } elseif ($recognition == Recognition::ALWAYS) // always
    {
        $userData = $this->getMethod()->getCustomerData();
    }
}
    
    
    
?>
<div class="form-list hcd-payment-info"
     id="payment_form_<?php echo $this->htmlEscape($code) ?>" style="display: none;">
    <div class="input-box">
        <label for="<?php echo $this->htmlEscape($code) ?>_holder"
               class="required hcd-singleline-label"><em>*</em>
            <?php echo $this->htmlEscape($this->__('Owner')) ?></label>

        <input type="text" title="<?php echo $this->htmlEscape($this->__('Owner')) ?>"
               class="input-text required-entry" id="<?php echo $this->htmlEscape($code); ?>_holder"
               name="payment[<?php echo $this->htmlEscape($code) ?>_holder]"
               value="<?php echo $this->htmlEscape(
                   isset($userData['payment_data']['ACCOUNT.HOLDER'])
                   ? $userData['payment_data']['ACCOUNT.HOLDER']  :$this->getMethod()->getCustomerName()
               ) ?>" />
    </div>
    <div class="input-box">
        <label for="<?php echo $this->htmlEscape($code) ?>_iban"
            class="required hcd-singleline-label"><em>*</em><?php echo $this->htmlEscape($this->__('IBAN')) ?></label>

        <input type="text" title="<?php echo $this->htmlEscape($this->__('IBAN')) ?>"
               class="input-text required-entry validate-alphanum" id="<?php echo $this->htmlEscape($code) ?>_iban"
            name="payment[<?php echo $this->htmlEscape($code) ?>_iban]"
               value="<?php if (isset($userData['payment_data']['ACCOUNT.IBAN'])) {
                   echo $this->htmlEscape($userData['payment_data']['ACCOUNT.IBAN']);
               } ?>"
            size="25">
    </div>
<div class="hcd-payment-desc">
        <?php echo $this->htmlEscape($this->__('Desc'.$code));?>
    </div>
</div>
