<?php

$_code = $this->getMethodCode ();

$path = "payment/" . $_code . "/";
$storeId = Mage::app ()->getStore ()->getId ();
$recognition = Mage::getStoreConfig ( $path . 'recognition', $storeId );
$insurence = Mage::getStoreConfig ( $path . 'insurence', $storeId );
/*
 * Look for customer recognition
 */

$hash = $this->getMethod ()->getShippingHash ();
$userData = array ();

$cId = $this->getMethod ()->getCustomerId ();

if ($recognition == 1 and $cId != 0) { // only if shipping address is unchanged
	$hash = $this->getMethod ()->getShippingHash ();
	$userData = $this->getMethod ()->getCustomerData ();
	if (array_key_exists ( 'payment_data', $userData )) {
		if ($userData ['payment_data'] ['SHIPPPING_HASH'] != $hash)
			$userData = array ();
	}
} elseif ($recognition == 2 and $cId != 0) // allways
	$userData = $this->getMethod ()->getCustomerData ();
	
	
	
?>
<div class="form-list hcd-payment-info"	id="payment_form_<?php echo $_code ?>" style="display: none;">
    <div class="input-box">
        <label for="<?php echo $_code ?>_holder"
               class="required hcd-singleline-label"><em>*</em><?php echo $this->__('Owner') ?></label>

        <input type="text" title="<?php echo $this->__('Owner:') ?>"
               class="input-text required-entry" id="<?php echo $_code ?>_holder"
               name="payment[<?php echo $_code ?>_holder]"
               value="<?php echo $this->htmlEscape((isset( $userData['payment_data']['ACCOUNT.HOLDER'])) ? $userData['payment_data']['ACCOUNT.HOLDER']  :$this->getMethod()->getCustomerName()) ?>" />
    </div>
	<div class="input-box">
		<label for="<?php echo $_code ?>_iban"
			class="required hcd-singleline-label"><em>*</em><?php echo $this->__('IBAN') ?></label>

		<input type="text" title="<?php echo $this->__('IBAN') ?>"  class="input-text required-entry validate-alphanum"			id="<?php echo $_code ?>_iban"
			name="payment[<?php echo $_code ?>_iban]" value="<?php if (isset($userData['payment_data']['ACCOUNT.IBAN'])) echo  $this->htmlEscape($userData['payment_data']['ACCOUNT.IBAN']) ; if (isset($userData['payment_data']['ACCOUNT.NUMBER'])) echo  $this->htmlEscape($userData['payment_data']['ACCOUNT.NUMBER']) ;  ?>"
			size="25">
	</div>
<div class="hcd-payment-desc">
    	<?php echo $this->__('Desc'.$_code);?>
    </div>
</div>