<?php
/**
 * Invoice secured form template
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present Heidelberger Payment GmbH. All rights reserved.
 *
 * @link  https://dev.heidelpay.de/magento
 *
 * @author  Jens Richter
 *
 * @package  Heidelpay
 * @subpackage Magento
 * @category Magento
 */
$code = $this->getMethodCode();
$dobyear = null;
$dobmounth = null;
$dobday = null;

$path = "payment/" . $code . "/";
$storeId = Mage::app()->getStore()->getId();
$recognition = Mage::getStoreConfig($path . 'recognition', $storeId);

$hash = $this->getMethod()->getShippingHash();
$userData = array();

$cId = $this->getMethod()->getCustomerId();

if ($recognition == 1 and $cId != 0) {
    // only if shipping address is unchanged
    $hash = $this->getMethod()->getShippingHash();
    $userData = $this->getMethod()->getCustomerData();
    if ($userData !== false and array_key_exists('payment_data', $userData)) {
        if ($userData ['payment_data'] ['SHIPPPING_HASH'] != $hash) {
            $userData = array();
        }
    }
} elseif ($recognition == 2 and $cId != 0) {
    $userData = $this->getMethod()->getCustomerData();
}

if (array_key_exists('payment_data', $userData) &&
    array_key_exists('NAME.BIRTHDATE', $userData['payment_data'])
) {
    list($dobyear, $dobmounth, $dobday) = explode('-', $userData['payment_data']['NAME.BIRTHDATE']);
}

?>
<div class="form-list hcd-payment-info" id="payment_form_<?php echo $this->htmlEscape($code) ?>" style="display: none;">
    <div class="input-box">
        <label for="<?php echo $this->htmlEscape($code) ?>_salutation"
               class="required hcd-singleline-label"><em>*</em><?php echo $this->htmlEscape($this->__('salutation')) ?>
        </label>
        <select title="<?php echo $this->htmlEscape($this->__('salutation')) ?>"
                name="payment[<?php echo $this->htmlEscape($code) ?>_salutation]">
            <option value="MR"><?php echo $this->htmlEscape($this->__('mr')) ?></option>
            <option value="MRS" <?php if (array_key_exists('payment_data', $userData) and
                array_key_exists('NAME.SALUTATION', $userData['payment_data']) and
                $userData['payment_data']['NAME.SALUTATION'] == 'MRS'
            ) echo 'selected="selected"' ?>>
                <?php echo $this->htmlEscape($this->__('mrs')) ?>
            </option>
        </select>
    </div>
    <div class="input-box">
        <label for="<?php echo $this->htmlEscape($code) ?>_dob"
               class="required hcd-singleline-label"><em>*</em>
            <?php echo $this->htmlEscape($this->__('Date of birth')) ?></label>
        <select title="<?php echo $this->htmlEscape($this->__('day')) ?>"
                name="payment[<?php echo $this->htmlEscape($code) ?>_dobday]">
            <option><?php echo $this->htmlEscape($this->__('day')); ?></option>
            <?php
            $i = 0;
            for ($i = 1; $i <= 31; $i++) {
                $v = sprintf("%02d", $i);
                $selected = ($dobday === $v) ? 'selected="selected"' : '';
                echo '<option value="' . $this->htmlEscape($v) . '" ' . $this->htmlEscape($selected)
                    . '>' . $this->htmlEscape($v) . '</option>';
            }
            ?>
        </select>
    </div>
    <div class="input-box">
        <select title="<?php echo $this->htmlEscape($this->__('month')) ?>"
                name="payment[<?php echo $this->htmlEscape($code) ?>_dobmonth]">
            <option><?php echo $this->htmlEscape($this->__('month')); ?></option>
            <?php
            $i = 0;
            for ($i = 1; $i <= 12; $i++) {
                $v = sprintf("%02d", $i);
                $selected = ($dobmounth == $v) ? 'selected="selected"' : '';
                echo '<option value="' . $this->htmlEscape($v) . '" ' . $this->htmlEscape($selected) . '>' .
                    $this->htmlEscape($v) . '</option>';
            }
            ?>
        </select>
    </div>
    <div class="input-box">
        <select title="<?php echo $this->htmlEscape($this->__('year')) ?>"
                name="payment[<?php echo $this->htmlEscape($code) ?>_dobyear]">
            <option><?php echo $this->htmlEscape($this->__('year')); ?></option>
            <?php
            $i = 0;
            for ($i = 17; $i <= 80; $i++) {
                // @codingStandardsIgnoreLine should be refactored - issue #2
                $year = date('Y', strtotime("last day of -$i year"));
                $selected = ($dobyear === $year) ? 'selected="selected"' : '';
                echo '<option value="' . $this->htmlEscape($year) . '" ' .
                    $this->htmlEscape($selected) . '>' . $this->htmlEscape($year) . '</option>';
            }
            ?>
        </select>
    </div>
    <div class="hcd-payment-desc">
        <?php echo $this->htmlEscape($this->__('Desc' . $code)); ?>
    </div>
</div>