<?php
/**
 * Description only form template
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present Heidelberger Payment GmbH. All rights reserved.
 *
 * @link  https://dev.heidelpay.de/magento
 *
 * @author  Jens Richter
 *
 * @package  Heidelpay
 * @subpackage Magento
 * @category Magento
 */
$code = $this->getMethodCode();

/** @var HeidelpayCD_Edition_Model_Payment_Abstract $payment */
$payment = $this->getMethod();
$data = $payment->getHeidelpayUrl(true);

$payment->log(print_r($data,1));

?>
<div class="form-list hcd-payment-info" id="payment_form_<?php echo $this->htmlEscape($code) ?>" style="display: none;">
    <div class="hcd-payment-desc">
        <?php echo $this->htmlEscape($this->__('Desc'.$code)); ?>
        Hallo Welt
    </div>
</div>
