<?php
/**
 * Invoice secured form template
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present Heidelberger Payment GmbH. All rights reserved.
 *
 * @link  https://dev.heidelpay.de/magento
 *
 * @author  Jens Richter
 *
 * @package  Heidelpay
 * @subpackage Magento
 * @category Magento
 */
$_code = $this->getMethodCode();

$path = "payment/" . $_code . "/";
$storeId = Mage::app()->getStore()->getId();
$recognition = Mage::getStoreConfig($path . 'recognition', $storeId);

$hash = $this->getMethod()->getShippingHash();
$userData = array();

$cId = $this->getMethod()->getCustomerId();

if ($recognition == 1 and $cId != 0) { // only if shipping address is unchanged
    $hash = $this->getMethod()->getShippingHash();
    $userData = $this->getMethod()->getCustomerData();
    if (array_key_exists('payment_data', $userData)) {
        if ($userData ['payment_data'] ['SHIPPPING_HASH'] != $hash) {
            $userData = array();
        }
    }
} elseif ($recognition == 2 and $cId != 0) // allways
{
    $userData = $this->getMethod()->getCustomerData();
}


?>
<div class="form-list hcd-payment-info" id="payment_form_<?php echo $_code ?>" style="display: none;">
    <div class="input-box">
        <label for="<?php echo $_code ?>_salutation"
               class="required hcd-singleline-label"><em>*</em><?php echo $this->__('salutation') ?></label>

        <select title="<?php echo $this->__('salutation') ?>" name="payment[<?php echo $_code ?>_salutation]"
                style="width: 75px">
            <option value="MR"><?php echo $this->__('mr') ?></option>
            <option value="MRS"><?php echo $this->__('mrs') ?></option>
        </select>
    </div>
    <div class="input-box">
        <label for="<?php echo $_code ?>_dob"
               class="required hcd-singleline-label"><em>*</em><?php echo $this->__('Date of birth') ?></label>
        <select title="<?php echo $this->__('day') ?>"
                name="payment[<?php echo $_code ?>_dobday]" style="width: 50px">
            <option><?php echo $this->__('day'); ?>/option>
                <?php
                $i = 0;
                for ($i = 1; $i <= 31; $i++) {
                    $v = sprintf("%02d", $i);
                    $selected = ($dobday === $v) ? 'selected="selected"' : '';
                    echo '<option value="' . $v . '" ' . $selected . '>' . $v . '</option>';
                }
                ?>
        </select>
        <select title="<?php echo $this->__('month') ?>"
                name="payment[<?php echo $_code ?>_dobmonth]">
            <option><?php echo $this->__('month'); ?></option>
            <?php
            $i = 0;
            for ($i = 1; $i <= 12; $i++) {
                $v = sprintf("%02d", $i);
                $selected = ($dobmounth == $v) ? 'selected="selected"' : '';
                echo '<option value="' . $v . '" ' . $selected . '>' . $v . '</option>';
            }
            ?>
        </select>
        <select title="<?php echo $this->__('year') ?>" name="payment[<?php echo $_code ?>_dobyear]"
                style="width: 75px">
            <option><?php echo $this->__('year'); ?></option>
            <?php
            $i = 0;
            for ($i = 17; $i <= 80; $i++) {
                $year = date('Y', strtotime("last day of -$i year"));
                $selected = ($dobyear === $year) ? 'selected="selected"' : '';
                echo '<option value="' . $year . '" ' . $selected . '>' . $year . '</option>';
            }
            ?>
        </select>
    </div>

</div>
<div class="hcd-payment-desc">
    <?php echo $this->__('Desc' . $_code); ?>
</div>