<?php
/**
 * Masterpass form template
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present Heidelberger Payment GmbH. All rights reserved.
 *
 * @link  https://dev.heidelpay.de/magento
 *
 * @author  Jens Richter
 *
 * @package  Heidelpay
 * @subpackage Magento
 * @category Magento
 */
$data = array();
$userData = array();
$payment = '';

$code=$this->getMethodCode();

?>
<div class="form-list hcd-payment-info" id="payment_form_<?php echo $this->htmlEscape($code) ?>" style="display: none;">
    <div class="hcd-payment-desc" style="border-left: 0px;">
        <button type="button" title="MasterPass"
            class="btn-hcdmpa-payment-data"
            onclick="window.open('https://www.mastercard.com/mc_us/wallet/learnmore/<?php 
    $lang = Mage::app()->getLocale()->getLocaleCode();
    switch ($lang) {
        case 'de_DE':
        case 'de_AT':
        case 'de_CH':
                echo 'de/DE';
            break;
        case 'fr_FR':
                echo 'fr/FR';
            break;
        case 'en_GB':
        default:
                echo 'en/US';
            break;
    }?>')"
    ></button>
        <div class="hcd-masterpass-payment-data">
        <?php 
        $mpadata = $this->getMethod()->getPaymentData(); 
        if (!empty($mpadata)) {
                echo $this->htmlEscape($mpadata);
        } else {
            echo '<p>'.$this->htmlEscape($this->__('Deschcdmpa')).'</p>';
        } ?>
        </div>
            
        
    </div>
</div>
