<?php
/**
 * Postfinance form template
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2016-present Heidelberger Payment GmbH. All rights reserved.
 *
 * @link  https://dev.heidelpay.de/magento
 *
 * @author  Jens Richter
 *
 * @package  Heidelpay
 * @subpackage Magento
 * @category Magento
 */
$code=$this->getMethodCode();
?>
<div class="form-list hcd-payment-info" id="payment_form_<?php echo $this->htmlEscape($code) ?>" style="display: none;">
        <div class="input-box">
            <input id="<?php echo $this->htmlEscape($code) ?>_pf" class="radio"
                   name="payment[<?php echo $this->htmlEscape($code) ?>_pf]"
                   value="PFEFINANCE" autocomplete="off" type="radio">

            </input>
            <label class="hco-inline-label">Post Finance E-Finance</label>
        </div>
        <div class="input-box">
            <input id="<?php echo $this->htmlEscape($code) ?>_pf" class="radio"
                   name="payment[<?php echo $this->htmlEscape($code) ?>_pf]"
                   value="PFCARD" autocomplete="off" type="radio">
             </input>
            <label class="hco-inline-label">Post Finance Card</label>
            <br style="clean:both;">
        </div>
        <div>
    <div class="hcd-payment-desc">
        <?php echo $this->htmlEscape($this->__('Deschcdpf'));?>
    </div>
    
</div>
