<?php
/**
 * Invoice by Santander form template
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2017-present Heidelberger Payment GmbH. All rights reserved.
 *
 * @link https://dev.heidelpay.de/magento-cd-edition
 *
 * @author Stephano Vogel
 *
 * @package heidelpay/magento-cd-edition/template/form/santander-invoice
 */

use HeidelpayCD_Edition_Model_System_Config_Source_Recognition as Recognition;

/** @var HeidelpayCD_Edition_Block_Form_SantanderInvoice $form */
$form = $this;
// set santander fields
$form->setSantanderInformation();

$code = $this->getMethodCode();
$dobyear = null;
$dobmonth = null;
$dobday = null;

$path = 'payment/' . $code . '/';
$storeId = Mage::app()->getStore()->getId();
$recognition = Mage::getStoreConfig($path . 'recognition', $storeId);

$hash = $this->getMethod()->getShippingHash();
$userData = array();

$cId = $this->getMethod()->getCustomerId();

if ($recognition == Recognition::SAME_SHIPPING_ADDRESS && $cId != 0) {
    // only if shipping address is unchanged
    $hash = $this->getMethod()->getShippingHash();
    $userData = $this->getMethod()->getCustomerData();
    if (!empty($userData) && array_key_exists('payment_data', $userData)) {
        if ($userData ['payment_data'] ['SHIPPING_HASH'] != $hash) {
            $userData = array();
        }
    }
} elseif ($recognition == Recognition::ALWAYS && $cId != 0) {
    $userData = $this->getMethod()->getCustomerData();
}

if (array_key_exists('payment_data', $userData) &&
    array_key_exists('NAME.BIRTHDATE', $userData['payment_data'])
) {
    list($dobyear, $dobmonth, $dobday) = explode('-', $userData['payment_data']['NAME.BIRTHDATE']);
}

?>
<div class="form-list fieldset hcd-payment-info" id="payment_form_<?php echo $this->htmlEscape($code) ?>" style="display: none;">
    <p class="required"><?php echo $this->htmlEscape($this->__('* Required Fields')) ?></p>
    <div>
        <img src="<?php echo $form->getImgLink() ?>" alt="Rechnungskauf von Santander" title="Rechnungskauf von Santander" />
    </div>
    <!-- Select Input for salutation -->
    <div class="input-box">
        <label for="<?php echo $this->htmlEscape($code) ?>_salutation"
               class="required hcd-singleline-label"><em>*</em><?php echo $this->htmlEscape($this->__('salutation')) ?>
        </label>
        <select class="required-entry"
                title="<?php echo $this->htmlEscape($this->__('salutation')) ?>"
                name="payment[<?php echo $this->htmlEscape($code) ?>_salutation]">
            <option value="MR"><?php echo $this->htmlEscape($this->__('mr')) ?></option>
            <option value="MRS" <?php
            if (array_key_exists('payment_data', $userData) &&
                array_key_exists('NAME.SALUTATION', $userData['payment_data']) &&
                $userData['payment_data']['NAME.SALUTATION'] === 'MRS'
            ) {
                echo 'selected="selected"';
            } ?>>
                <?php echo $this->htmlEscape($this->__('mrs')) ?>
            </option>
        </select>
    </div>
    <!-- Select Input for date of birth (day) -->
    <div class="input-box">
        <label for="<?php echo $this->htmlEscape($code) ?>_dob"
               class="required hcd-singleline-label"><em>*</em>
            <?php echo $this->htmlEscape($this->__('Date of birth')) ?></label>
        <select class="required-entry"
                title="<?php echo $this->htmlEscape($this->__('day')) ?>"
                name="payment[<?php echo $this->htmlEscape($code) ?>_dobday]">
            <option disabled <?php echo $dobday === null ? 'selected' : ''; ?> value>
                <?php echo $this->htmlEscape($this->__('day')); ?>
            </option>
            <?php
            $i = 0;
            for ($i = 1; $i <= 31; $i++) {
                $v = sprintf('%02d', $i);
                $selected = ($dobday === $v) ? 'selected="selected"' : '';
                echo '<option value="' . $this->htmlEscape($v) . '" ' . $this->htmlEscape($selected)
                    . '>' . $this->htmlEscape($v) . '</option>';
            }
            ?>
        </select>
    </div>
    <!-- Select Input for date of birth (month) -->
    <div class="input-box">
        <select class="required-entry"
                title="<?php echo $this->htmlEscape($this->__('month')) ?>"
                name="payment[<?php echo $this->htmlEscape($code) ?>_dobmonth]">
            <option disabled <?php echo $dobmonth === null ? 'selected' : ''; ?> value>
                <?php echo $this->htmlEscape($this->__('month')); ?>
            </option>
            <?php
            $i = 0;
            for ($i = 1; $i <= 12; $i++) {
                $v = sprintf('%02d', $i);
                $selected = ($dobmonth == $v) ? 'selected="selected"' : '';
                echo '<option value="' . $this->htmlEscape($v) . '" ' . $this->htmlEscape($selected) . '>' .
                    $this->htmlEscape($v) . '</option>';
            }
            ?>
        </select>
    </div>
    <!-- Select Input for date of birth (year) -->
    <div class="input-box">
        <select class="required-entry"
                title="<?php echo $this->htmlEscape($this->__('year')) ?>"
                name="payment[<?php echo $this->htmlEscape($code) ?>_dobyear]">
            <option disabled <?php echo $dobyear === null ? 'selected' : ''; ?> value>
                <?php echo $this->htmlEscape($this->__('year')); ?>
            </option>
            <?php
            $i = 0;
            for ($i = 17; $i <= 80; $i++) {
                // @codingStandardsIgnoreLine should be refactored - issue #2
                $year = date('Y', strtotime("last day of -$i year"));
                $selected = ($dobyear === $year) ? 'selected="selected"' : '';
                echo '<option value="' . $this->htmlEscape($year) . '" ' .
                    $this->htmlEscape($selected) . '>' . $this->htmlEscape($year) . '</option>';
            }
            ?>
        </select>
    </div>

    <!-- Santander Agreements -->
    <div class="<?php echo $code; ?>">
        <!-- Santander advertising opt-out -->
        <div class="input-box <?php echo $code ?>-adv-optout">
            <h4>Werbezustimmung</h4>
            <p class="control">
                <input type="checkbox" class="checkbox" name="payment[<?php echo $code ?>_adv_optout]" id="<?php echo $code ?>-adv-optout" />
                <label for="<?php echo $code ?>-adv-optout"><?php echo $form->getAdvText(); ?></label>
            </p>
        </div>

        <!-- Santander privacy policy opt-in -->
        <div class="input-box <?php echo $code ?>-privpol-optin">
            <h4>Datenschutzerklärung</h4>
            <p class="control">
                <input type="checkbox" class="checkbox required-entry" name="payment[<?php echo $code ?>_privpol_optin]" id="<?php echo $code ?>-privpol-optin" />
                <label class="required" for="<?php echo $code ?>-privpol-optin"><?php echo $form->getPrivpolText(); ?></label>
            </p>
        </div>
        <div class="hcd-payment-desc">
            <?php echo $this->htmlEscape($this->__('Desc' . $code)); ?>
        </div>
    </div>
</div>