<?php
/**
 * Invoice by Santander form template
 *
 * @license Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 * @copyright Copyright © 2017-present Heidelberger Payment GmbH. All rights reserved.
 *
 * @link https://dev.heidelpay.de/magento-cd-edition
 *
 * @author Stephano Vogel
 *
 * @package heidelpay/magento-cd-edition/template/form/santander-invoice
 */

use HeidelpayCD_Edition_Model_System_Config_Source_Recognition as Recognition;

/** @var HeidelpayCD_Edition_Block_Form_SantanderInvoice $form */
$form = $this;
/** @var HeidelpayCD_Edition_Model_Payment_Abstract $paymentMethod */
$paymentMethod = $form->getMethod();

// set santander form fields
$form->setSantanderInformation();

$code = $form->getMethodCode();
$dobyear = null;
$dobmonth = null;
$dobday = null;

$userSalutation = null;

$path = 'payment/' . $code . '/';
$storeId = Mage::app()->getStore()->getId();
$recognition = Mage::getStoreConfig($path . 'recognition', $storeId);

$userData = array();
$customerId = $paymentMethod->getCustomerId();

if ($recognition == Recognition::SAME_SHIPPING_ADDRESS && $customerId != 0) {
    // only if shipping address is unchanged
    $hash = $paymentMethod->getShippingHash();
    $userData = $paymentMethod->getCustomerData();

    if (array_key_exists('payment_data', $userData) &&
        array_key_exists('NAME.BIRTHDATE', $userData['payment_data'])
    ) {
        list($dobyear, $dobmonth, $dobday) = explode('-', $userData['payment_data']['NAME.BIRTHDATE']);
    }

    // if a shipping hash is present, but not the same as a one saved before, do not use recognized data.
    if (!empty($userData) && array_key_exists('payment_data', $userData)
        && isset($userData['payment_data']['SHIPPING_HASH'])
        && $userData['payment_data']['SHIPPING_HASH'] !== $hash
    ) {
        $userData = array();
    }
} elseif ($recognition == Recognition::ALWAYS && $customerId != 0) {
    $userData = $paymentMethod->getCustomerData();

    if (array_key_exists('payment_data', $userData) &&
        array_key_exists('NAME.BIRTHDATE', $userData['payment_data'])
    ) {
        list($dobyear, $dobmonth, $dobday) = explode('-', $userData['payment_data']['NAME.BIRTHDATE']);
    }
}


if (isset($userData['payment_data']['NAME.SALUTATION'])) {
    $userSalutation = $userData['payment_data']['NAME.SALUTATION'];
}

?>
<div class="form-list fieldset hcd-payment-info" id="payment_form_<?php echo $form->escapeHtml($code) ?>" style="display: none;">
    <p class="required"><?php echo $form->escapeHtml($form->__('* Required Fields')) ?></p>
    <div>
        <img src="<?php echo $form->getImgLink() ?>" alt="Rechnungskauf von Santander" title="Rechnungskauf von Santander" />
    </div>
    <!-- Select Input for salutation -->
    <div class="input-box">
        <label for="<?php echo $form->escapeHtml($code) ?>_salutation"
               class="required hcd-singleline-label"><em>*</em><?php echo $form->escapeHtml($form->__('salutation')) ?>
        </label>
        <select class="required-entry"
                title="<?php echo $form->escapeHtml($form->__('salutation')) ?>"
                name="payment[<?php echo $form->escapeHtml($code) ?>_salutation]">
            <option disabled value="" <?php echo $userSalutation === null ? 'selected="selected"' : ''; ?>>
                <?php echo $form->escapeHtml($form->__('Please choose your salution')) ?>
            </option>
            <option value="MR" <?php echo $userSalutation === 'MR' ? 'selected="selected"' : ''; ?>>
                <?php echo $form->escapeHtml($form->__('mr')) ?>
            </option>
            <option value="MRS" <?php echo $userSalutation === 'MRS' ? 'selected="selected"' : ''; ?>>
                <?php echo $form->escapeHtml($form->__('mrs')) ?>
            </option>
        </select>
    </div>
    <!-- Select Input for date of birth (day) -->
    <div class="input-box">
        <label for="<?php echo $form->escapeHtml($code) ?>_dob"
               class="required hcd-singleline-label"><em>*</em>
            <?php echo $form->escapeHtml($form->__('Date of birth')) ?></label>
        <select class="required-entry"
                title="<?php echo $form->escapeHtml($form->__('day')) ?>"
                name="payment[<?php echo $form->escapeHtml($code) ?>_dobday]">
            <option disabled <?php echo $dobday === null ? 'selected' : ''; ?> value>
                <?php echo $form->escapeHtml($form->__('day')); ?>
            </option>
            <?php
            $i = 0;
            for ($i = 1; $i <= 31; $i++) {
                $v = sprintf('%02d', $i);
                $selected = ($dobday === $v) ? 'selected="selected"' : '';
                echo '<option value="' . $form->escapeHtml($v) . '" ' . $form->escapeHtml($selected)
                    . '>' . $form->escapeHtml($v) . '</option>';
            }
            ?>
        </select>
    </div>
    <!-- Select Input for date of birth (month) -->
    <div class="input-box">
        <select class="required-entry"
                title="<?php echo $form->escapeHtml($form->__('month')) ?>"
                name="payment[<?php echo $form->escapeHtml($code) ?>_dobmonth]">
            <option disabled <?php echo $dobmonth === null ? 'selected' : ''; ?> value>
                <?php echo $form->escapeHtml($form->__('month')); ?>
            </option>
            <?php
            $i = 0;
            for ($i = 1; $i <= 12; $i++) {
                $v = sprintf('%02d', $i);
                $selected = ($dobmonth === $v) ? 'selected="selected"' : '';
                echo '<option value="' . $form->escapeHtml($v) . '" ' . $form->escapeHtml($selected) . '>' .
                    $form->escapeHtml($v) . '</option>';
            }
            ?>
        </select>
    </div>
    <!-- Select Input for date of birth (year) -->
    <div class="input-box">
        <select class="required-entry"
                title="<?php echo $form->escapeHtml($form->__('year')) ?>"
                name="payment[<?php echo $form->escapeHtml($code) ?>_dobyear]">
            <option disabled <?php echo $dobyear === null ? 'selected' : ''; ?> value>
                <?php echo $form->escapeHtml($form->__('year')); ?>
            </option>
            <?php
            $i = 0;
            for ($i = 17; $i <= 80; $i++) {
                // @codingStandardsIgnoreLine should be refactored - issue #2
                $year = date('Y', strtotime("last day of -$i year"));
                $selected = ($dobyear === $year) ? 'selected="selected"' : '';
                echo '<option value="' . $form->escapeHtml($year) . '" ' .
                    $form->escapeHtml($selected) . '>' . $form->escapeHtml($year) . '</option>';
            }
            ?>
        </select>
    </div>

    <!-- Santander Agreements -->
    <div class="<?php echo $code; ?>">
        <!-- Santander advertising opt-out -->
        <div class="input-box <?php echo $code ?>-adv-optout">
            <h4>Werbezustimmung</h4>
            <p class="control">
                <input type="checkbox" class="checkbox" name="payment[<?php echo $code ?>_adv_optout]" id="<?php echo $code ?>-adv-optout" />
                <label for="<?php echo $code ?>-adv-optout"><?php echo $form->getAdvText(); ?></label>
            </p>
        </div>

        <!-- Santander privacy policy opt-in -->
        <div class="input-box <?php echo $code ?>-privpol-optin">
            <h4>Datenschutzerklärung</h4>
            <p class="control">
                <input type="checkbox" class="checkbox required-entry" name="payment[<?php echo $code ?>_privpol_optin]" id="<?php echo $code ?>-privpol-optin" />
                <label class="required" for="<?php echo $code ?>-privpol-optin"><?php echo $form->getPrivpolText(); ?></label>
            </p>
        </div>
        <div class="hcd-payment-desc">
            <?php echo $form->escapeHtml($form->__('Desc' . $code)); ?>
        </div>
    </div>
</div>